### ISSUE TITLE
How to run...

### ISSUE THREAD

**Issue by yaichenbaum** [5E7EN/K9-Password-Finder#1]
Does this need to be compiled or can it just be downloaded and ran?

**Comment by 5E7EN** [comment]
The instructions listed in the README file are to compile the program on your own. The executable can be found on the [releases](https://github.com/5E7EN/K9-Password-Finder/releases) page.

**Comment by yaichenbaum** [comment]
Thank you!

**Comment by 5E7EN** [comment]
No problem 👍
